name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install server deps
        run: npm ci --workspace=server
      - name: Generate Prisma client
        run: npm --prefix server run prisma:generate
      - name: Run server tests
        run: npm --prefix server test
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install web deps
        run: npm ci --workspace=web
      - name: Build web
        run: npm --prefix web run build