const express = require('express')
const bodyParser = require('body-parser')
const pillars = require('./routes/pillars')
const tx = require('./routes/transactions')
const prisma = require('./prismaClient')
const { PORT } = require('./config')
const app = express()
app.use(bodyParser.json())
app.use('/api/pillars', pillars)
app.use('/api/tx', tx)
app.get('/health', (req, res) => res.json({ status: 'ok' }))
app.listen(PORT, () => console.log('Server running on port', PORT))
process.on('SIGINT', async () => { await prisma.$disconnect(); process.exit(0) })